### ISSUE TITLE
ARM runtime is outdated

### ISSUE THREAD

**Issue by philn** [Igalia/wpe-flatpak#4]
```
$ pkg-config --modversion wpebackend-fdo-1.0
1.6.0
$ pkg-config --modversion wpe-webkit-1.0
2.28.2
```

SDK manifest has -fdo 1.8.3 and wpewebkit 2.32.0. cc @zdobersek

**Comment by zdobersek** [comment]
These aren't updated because the underlying fdo SDK removed support for arm:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1105

**Comment by philn** [comment]
Ah right, I forgot about this... :(

**Comment by zdobersek** [comment]
Should these outdated refs be removed?

**Comment by philn** [comment]
> Should these outdated refs be removed?

Once we move to 21.08 yeah. For now it's ok to keep them I suppose, I guess I was the only one trying to use this.
